name: chess_game
description: A Flutter application for a two-player chess game.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"  # Updated SDK constraint

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5  # Updated provider version
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/pieces/

